# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectname', models.CharField(max_length=10)),
                ('objectnum', models.CharField(max_length=3)),
            ],
        ),
    ]
