# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_user_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file',
            field=models.FileField(null=True, upload_to='./upload'),
        ),
    ]
