# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_auto_20170320_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='objectname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='object',
            old_name='objectnum',
            new_name='num',
        ),
        migrations.AddField(
            model_name='object',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.Object'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.User'),
        ),
    ]
