# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_auto_20170320_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='img',
            field=models.FileField(default='static/img/default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='object',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
