# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_auto_20170320_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='img',
            field=models.FileField(default='static/img/default.png', upload_to='static/img/'),
        ),
    ]
