# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_auto_20170322_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='active', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='head_pic',
            field=models.FileField(default='static/img/default.png', upload_to='static/img/'),
        ),
    ]
