# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_auto_20170406_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='img',
            field=models.FileField(default='/static/img/default.png', upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='head_pic',
            field=models.FileField(default='/static/img/default.png', upload_to='static/img/'),
        ),
    ]
