# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_auto_20170406_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head_pic',
            field=models.FileField(default='static/img/default.png', upload_to='static/img/'),
        ),
    ]
